# Generated by Django 3.0.8 on 2020-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('userName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=75)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('userGroup', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('fixed', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('form', models.CharField(max_length=20)),
                ('until', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('userName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=75)),
                ('password', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
