# Generated by Django 3.0.8 on 2020-07-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='game',
        ),
    ]
